<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ5jexcm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ5jexcm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJ5jexcm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJ5jexcm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJ5jexcm\appProdProjectContainer([
    'container.build_hash' => 'J5jexcm',
    'container.build_id' => '0b4d83af',
    'container.build_time' => 1640702327,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ5jexcm');
